/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>
#include <string.h>

#include "UART.h"
#include "I2C.h"
#include "temp.h"

char temp_str[32];
char pressure_str[32];

void delay(void)
{
	for(uint32_t i =0 ; i<250000 ; i++);
}


int main(void)
{
	int32_t temp;
	int32_t press;

	uart2_tx_init();
    I2C1_GPIO_Init();
    I2C1_Init();
    I2C1_EN();
    if (BMP280_Init() == 0) {
        printf("BMP280 Init Failed.\r\n");
        while(1);
    } else {
        printf("BMP280 Init Success.\r\n");
    }

    while(1)
        {
            temp = BMP280_ReadTemperature();
            press = BMP280_ReadPressure();

            //Calculations to process values of temperature and pressure
            int32_t t_int = temp / 100;
            int32_t t_dec = temp % 100;
            uint32_t p_pa = press / 256;
            uint32_t p_int = p_pa / 100;
            uint32_t p_dec = p_pa % 100;


            sprintf(temp_str, "Temperature: %ld.%02ld C", t_int, t_dec);
            sprintf(pressure_str, "Pressure: %ld.%02ld hPa", p_int, p_dec);

            printf("%s \r\n", temp_str);
            printf("%s \r\n", pressure_str);

            delay();
        }
}
